services:
  mysql:
    container_name: 'backlog-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=backlog'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=mies'
    ports:
      - '3306:3306'